# Generated by Django 3.2 on 2022-10-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pick',
            field=models.CharField(choices=[('BLUE', 'ISSUE_A'), ('RED', 'ISSUE_B')], max_length=10),
        ),
    ]
