# Generated by Django 3.2 on 2022-10-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0002_alter_comment_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pick',
            field=models.CharField(choices=[('BLUE', 'BLUE'), ('RED', 'RED')], max_length=10),
        ),
    ]
