# Generated by Django 3.2 on 2022-10-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavingDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=50)),
                ('fin_co_no', models.CharField(max_length=50)),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('kor_co_nm', models.CharField(max_length=50)),
                ('fin_prdt_nm', models.CharField(max_length=50)),
                ('join_way', models.CharField(max_length=50, null=True)),
                ('mtrt_int', models.CharField(max_length=200, null=True)),
                ('spcl_cnd', models.CharField(max_length=50, null=True)),
                ('join_deny', models.CharField(max_length=50, null=True)),
                ('join_member', models.CharField(max_length=50, null=True)),
                ('etc_note', models.CharField(max_length=200, null=True)),
                ('max_limit', models.CharField(max_length=50, null=True)),
                ('dcls_strt_day', models.CharField(max_length=50, null=True)),
                ('dcls_end_day', models.CharField(max_length=50, null=True)),
                ('fin_co_subm_day', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
