# Generated by Django 3.2.13 on 2022-10-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('코미디', 'comedy'), ('공포', 'horror'), ('로맨스', 'romance')], max_length=30),
        ),
    ]
