# Generated by Django 3.2.13 on 2022-10-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('comedy', '코미디'), ('horror', '공포'), ('romance', '로맨스')], max_length=30),
        ),
    ]
